// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/vault/read-model': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vault/read-model.get').default>>>>
    }
    '/api/vault/tasks': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vault/tasks.post').default>>>>
    }
    '/api/vault/tasks/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vault/tasks/[id]').default>>>>
    }
    '/api/vault/tasks/:id/approve': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vault/tasks/[id]/approve').default>>>>
    }
    '/api/vault/tasks/:id/claim': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vault/tasks/[id]/claim').default>>>>
    }
    '/api/vault/tasks/:id/heartbeat': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vault/tasks/[id]/heartbeat').default>>>>
    }
    '/api/vault/tasks/:id/reject': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vault/tasks/[id]/reject').default>>>>
    }
    '/api/vault/tasks/:id/request-approval': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vault/tasks/[id]/request-approval').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}