import { describe, expect, test } from "bun:test";

import type { VaultReadModel } from "../../models/read-model";

import { aggregateAgentAnalytics, aggregateCostAnalytics, aggregateVelocityAnalytics } from "./summary";

function createReadModel(): VaultReadModel {
  return {
    workspaces: [],
    projects: [
      {
        id: "project-alpha",
        type: "project",
        workspaceId: "ws-1",
        name: "Alpha",
        description: null,
        budget: null,
        deadline: null,
        status: null,
        links: [],
        attachments: [],
        codebases: [],
        boardIds: ["board-1"],
        columnIds: ["todo", "done"],
        taskIds: ["task-1", "task-2"],
        approvalIds: [],
        createdAt: "2026-04-01T00:00:00Z",
        updatedAt: "2026-04-01T00:00:00Z",
        body: "",
        sourcePath: "vault/shared/projects/project-alpha.md",
      },
      {
        id: "project-beta",
        type: "project",
        workspaceId: "ws-1",
        name: "Beta",
        description: null,
        budget: null,
        deadline: null,
        status: null,
        links: [],
        attachments: [],
        codebases: [],
        boardIds: ["board-2"],
        columnIds: ["todo", "done"],
        taskIds: ["task-3", "task-4"],
        approvalIds: [],
        createdAt: "2026-04-01T00:00:00Z",
        updatedAt: "2026-04-01T00:00:00Z",
        body: "",
        sourcePath: "vault/shared/projects/project-beta.md",
      },
    ],
    boards: [],
    columns: [],
    tasks: [
      {
        id: "task-1",
        type: "task",
        workspaceId: "ws-1",
        projectId: "project-alpha",
        boardId: "board-1",
        columnId: "done",
        status: "done",
        priority: "high",
        title: "Alpha complete",
        assignee: "agent-a",
        createdBy: "@owner",
        createdAt: "2026-04-01T00:00:00Z",
        updatedAt: "2026-04-05T00:00:00Z",
        heartbeatAt: null,
        executionStartedAt: "2026-04-02T00:00:00Z",
        executionNotes: null,
        progress: 100,
        approvalNeeded: true,
        approvalRequestedBy: null,
        approvalReason: null,
        approvedBy: "@owner",
        approvedAt: "2026-04-05T00:00:00Z",
        approvalOutcome: "approved",
        blockedReason: null,
        blockedSince: null,
        result: null,
        completedAt: "2026-04-05T00:00:00Z",
        tokensUsed: 1000,
        model: "claude-sonnet",
        costUsd: 2.5,
        parentTaskId: null,
        sourceIssueId: null,
        githubIssueId: null,
        dependsOn: [],
        tags: [],
        links: [],
        lockedBy: null,
        lockedAt: null,
        lockExpiresAt: null,
        isStale: false,
        approvalIds: [],
        approvalState: { status: "approved", needed: true, outcome: "approved", requestedBy: null, requestedAt: null, decidedBy: "@owner", decidedAt: "2026-04-05T00:00:00Z", reason: null },
        body: "",
        sourcePath: "vault/shared/tasks/task-1.md",
      },
      {
        id: "task-2",
        type: "task",
        workspaceId: "ws-1",
        projectId: "project-alpha",
        boardId: "board-1",
        columnId: "done",
        status: "review",
        priority: "medium",
        title: "Alpha review",
        assignee: "agent-a",
        createdBy: "@owner",
        createdAt: "2026-04-06T00:00:00Z",
        updatedAt: "2026-04-10T00:00:00Z",
        heartbeatAt: null,
        executionStartedAt: null,
        executionNotes: null,
        progress: 100,
        approvalNeeded: false,
        approvalRequestedBy: null,
        approvalReason: null,
        approvedBy: null,
        approvedAt: null,
        approvalOutcome: "pending",
        blockedReason: null,
        blockedSince: null,
        result: null,
        completedAt: null,
        tokensUsed: 500,
        model: "claude-sonnet",
        costUsd: 1.25,
        parentTaskId: null,
        sourceIssueId: null,
        githubIssueId: null,
        dependsOn: [],
        tags: [],
        links: [],
        lockedBy: null,
        lockedAt: null,
        lockExpiresAt: null,
        isStale: false,
        approvalIds: [],
        approvalState: { status: "not-needed", needed: false, outcome: "pending", requestedBy: null, requestedAt: null, decidedBy: null, decidedAt: null, reason: null },
        body: "",
        sourcePath: "vault/shared/tasks/task-2.md",
      },
      {
        id: "task-3",
        type: "task",
        workspaceId: "ws-1",
        projectId: "project-beta",
        boardId: "board-2",
        columnId: "done",
        status: "done",
        priority: "medium",
        title: "Beta complete",
        assignee: "agent-b",
        createdBy: "@owner",
        createdAt: "2026-04-08T00:00:00Z",
        updatedAt: "2026-04-18T00:00:00Z",
        heartbeatAt: null,
        executionStartedAt: "2026-04-09T00:00:00Z",
        executionNotes: null,
        progress: 100,
        approvalNeeded: true,
        approvalRequestedBy: null,
        approvalReason: null,
        approvedBy: null,
        approvedAt: null,
        approvalOutcome: "rejected",
        blockedReason: null,
        blockedSince: null,
        result: null,
        completedAt: "2026-04-18T00:00:00Z",
        tokensUsed: 2000,
        model: "claude-opus",
        costUsd: 5,
        parentTaskId: null,
        sourceIssueId: null,
        githubIssueId: null,
        dependsOn: [],
        tags: [],
        links: [],
        lockedBy: null,
        lockedAt: null,
        lockExpiresAt: null,
        isStale: false,
        approvalIds: [],
        approvalState: { status: "rejected", needed: true, outcome: "rejected", requestedBy: null, requestedAt: null, decidedBy: "@owner", decidedAt: "2026-04-18T00:00:00Z", reason: null },
        body: "",
        sourcePath: "vault/shared/tasks/task-3.md",
      },
      {
        id: "task-4",
        type: "task",
        workspaceId: "ws-1",
        projectId: "project-beta",
        boardId: "board-2",
        columnId: "todo",
        status: "blocked",
        priority: "low",
        title: "Beta stuck",
        assignee: "agent-b",
        createdBy: "@owner",
        createdAt: "2026-04-20T00:00:00Z",
        updatedAt: "2026-04-21T00:00:00Z",
        heartbeatAt: null,
        executionStartedAt: "2026-04-20T00:00:00Z",
        executionNotes: null,
        progress: 30,
        approvalNeeded: false,
        approvalRequestedBy: null,
        approvalReason: null,
        approvedBy: null,
        approvedAt: null,
        approvalOutcome: "pending",
        blockedReason: "Waiting on dependency",
        blockedSince: "2026-04-21T00:00:00Z",
        result: null,
        completedAt: null,
        tokensUsed: null,
        model: null,
        costUsd: null,
        parentTaskId: null,
        sourceIssueId: null,
        githubIssueId: null,
        dependsOn: [],
        tags: [],
        links: [],
        lockedBy: null,
        lockedAt: null,
        lockExpiresAt: null,
        isStale: true,
        approvalIds: [],
        approvalState: { status: "not-needed", needed: false, outcome: "pending", requestedBy: null, requestedAt: null, decidedBy: null, decidedAt: null, reason: null },
        body: "",
        sourcePath: "vault/shared/tasks/task-4.md",
      },
    ],
    issues: [],
    approvals: [],
    auditNotes: [],
    docs: [],
    agents: [
      {
        id: "agent-a",
        type: "agent",
        workspaceId: "ws-1",
        name: "Agent A",
        role: "implementation",
        roles: ["implementation"],
        provider: "claude",
        model: "claude-sonnet",
        fallbackModels: [],
        capabilities: [],
        taskTypesAccepted: [],
        approvalRequiredFor: [],
        cannotDo: [],
        accessibleBy: [],
        skillFile: "skills/agent-a.md",
        status: "active",
        createdAt: "2026-04-01T00:00:00Z",
        updatedAt: "2026-04-01T00:00:00Z",
        body: "",
        sourcePath: "vault/shared/agents/agent-a.md",
        accountId: null,
        apiKeyRef: null,
        monthlyBudgetUsd: 10,
      },
      {
        id: "agent-b",
        type: "agent",
        workspaceId: "ws-1",
        name: "Agent B",
        role: "implementation",
        roles: ["implementation"],
        provider: "claude",
        model: "claude-opus",
        fallbackModels: [],
        capabilities: [],
        taskTypesAccepted: [],
        approvalRequiredFor: [],
        cannotDo: [],
        accessibleBy: [],
        skillFile: "skills/agent-b.md",
        status: "active",
        createdAt: "2026-04-01T00:00:00Z",
        updatedAt: "2026-04-01T00:00:00Z",
        body: "",
        sourcePath: "vault/shared/agents/agent-b.md",
        accountId: null,
        apiKeyRef: null,
        monthlyBudgetUsd: 20,
      },
    ],
  };
}

describe("analytics summary aggregation", () => {
  test("aggregates cost by day and project", () => {
    const result = aggregateCostAnalytics(createReadModel());

    expect(result.totals.costUsd).toBe(8.75);
    expect(result.totals.tokensUsed).toBe(3500);
    expect(result.byProject[0]?.projectId).toBe("project-beta");
    expect(result.byDay).toHaveLength(3);
  });

  test("aggregates weekly completion counts and percentile lead times", () => {
    const result = aggregateVelocityAnalytics(createReadModel());

    expect(result.totals.completedCount).toBe(3);
    expect(result.totals.p50DaysToComplete).toBe(4);
    expect(result.totals.p95DaysToComplete).toBe(9);
    expect(result.completedPerWeek.length).toBeGreaterThan(0);
  });

  test("builds agent scorecards with stuck counts and approval rate", () => {
    const result = aggregateAgentAnalytics(createReadModel());
    const agentA = result.scorecards.find((entry) => entry.agentId === "agent-a");
    const agentB = result.scorecards.find((entry) => entry.agentId === "agent-b");

    expect(agentA?.approvalRate).toBe(100);
    expect(agentA?.completedTaskCount).toBe(2);
    expect(agentB?.stuckCount).toBe(1);
    expect(agentB?.approvalRate).toBe(0);
  });
});
