import { describe, expect, test } from "bun:test";

import { resumeAgentTask } from "./resume.post";

describe("POST /api/agent/[id]/resume", () => {
  test("forces resume mode and defaults surface to background", async () => {
    const response = await resumeAgentTask("claude-code", {
      taskId: "  task-001  ",
      previousSessionId: "runner-0",
    }, {
      resolveRoot: () => "/tmp/relayhq-vault",
      readModelReader: async () => ({
        workspaces: [{ id: "ws-demo", type: "workspace", name: "Demo", ownerIds: [], memberIds: [], projectIds: [], boardIds: [], columnIds: [], taskIds: [], approvalIds: [], createdAt: "2026", updatedAt: "2026", body: "", sourcePath: "vault/shared/workspaces/ws-demo.md" }],
        projects: [],
        boards: [],
        columns: [],
        tasks: [{
          id: "task-001",
          type: "task",
          workspaceId: "ws-demo",
          projectId: "project-demo",
          boardId: "board-demo",
          columnId: "todo",
          status: "todo",
          priority: "high",
          title: "Demo task",
          assignee: "claude-code",
          createdBy: "@alice",
          createdAt: "2026-04-23T12:00:00Z",
          updatedAt: "2026-04-23T12:00:00Z",
          heartbeatAt: null,
          executionStartedAt: null,
          executionNotes: null,
          progress: 0,
          history: [],
          dispatchStatus: null,
          dispatchReason: null,
          lastDispatchAttemptAt: null,
          nextRunAt: null,
          cronSchedule: null,
          approvalNeeded: false,
          approvalRequestedBy: null,
          approvalReason: null,
          approvedBy: null,
          approvedAt: null,
          approvalOutcome: "pending",
          blockedReason: null,
          blockedSince: null,
          result: null,
          completedAt: null,
          tokensUsed: null,
          model: null,
          costUsd: null,
          parentTaskId: null,
          sourceIssueId: null,
          githubIssueId: null,
          dependsOn: [],
          tags: [],
          links: [],
          lockedBy: null,
          lockedAt: null,
          lockExpiresAt: null,
          isStale: false,
          approvalIds: [],
          approvalState: { status: "not-needed", needed: false, outcome: "pending", requestedBy: null, requestedAt: null, decidedBy: null, decidedAt: null, reason: null },
          body: "",
          sourcePath: "vault/shared/tasks/task-001.md",
        }],
        issues: [],
        docs: [],
        approvals: [],
        auditNotes: [],
        agents: [{
          id: "claude-code",
          type: "agent",
          workspaceId: "ws-demo",
          name: "Claude Code",
          accountId: null,
          role: "implementation",
          roles: ["implementation"],
          provider: "claude",
          apiKeyRef: null,
          portraitAsset: null,
          spriteAsset: null,
          model: "claude-sonnet-4-6",
          fallbackModels: [],
          monthlyBudgetUsd: null,
          aliases: [],
          runtimeKind: "claude-code",
          runCommand: null,
          commandTemplate: null,
          runMode: null,
          webhookUrl: null,
          workingDirectoryStrategy: null,
          supportsResume: true,
          supportsStreaming: true,
          bootstrapStrategy: null,
          verificationStatus: "ready",
          capabilities: [],
          taskTypesAccepted: [],
          approvalRequiredFor: [],
          cannotDo: [],
          accessibleBy: [],
          skillFile: "skills/claude-code.md",
          skillFiles: [],
          status: "available",
          projectId: null,
          createdAt: "2026-04-23T00:00:00Z",
          updatedAt: "2026-04-23T00:00:00Z",
          body: "",
          sourcePath: "vault/shared/agents/claude-code.md",
        }],
      } as never),
      workspaceIdReader: () => null,
      launchAgentSession: async (request) => ({
        sessionId: request.previousSessionId ?? "runner-new",
        runnerId: "runner-new",
        agentId: request.agentId,
        taskId: request.taskId,
        runtimeKind: "claude-code",
        launchSurface: request.surface ?? "background",
        launchMode: request.mode ?? "fresh",
        command: "claude",
        args: ["-p"],
      }),
    })

    expect(response.launchMode).toBe("resume")
    expect(response.launchSurface).toBe("background")
    expect(response.sessionId).toBe("runner-0")
  })

  test("rejects missing task ids", async () => {
    await expect(resumeAgentTask("claude-code", { taskId: "   " })).rejects.toMatchObject({ statusCode: 400 })
  })
})
